services:
  # Ollama service: will provide api access to both LLM and embedding model
  ollama:
    image: ollama/ollama:0.13.0
    ports:
      - 11434:11434
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    volumes:
      - ./install-ollama-models.sh:/install-ollama-models.sh
    entrypoint: ["/usr/bin/bash", "/install-ollama-models.sh"]
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    networks:
      - ollama-docker

  # Elasticsearch service: will provide vector database functionality
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:9.1.7
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false

      # config otherwise elasticvue browser access will complain
      - http.cors.enabled=true
      - http.cors.allow-origin=http://localhost:8081
      - http.cors.allow-headers=Authorization,Content-Type,X-Requested-With
      - http.cors.allow-credentials=true

  # Elasticvue service: web interface for Elasticsearch
  elasticvue:
    container_name: elasticvue
    image: cars10/elasticvue
    ports:
      - 8081:8080
    depends_on:
      - elasticsearch

  redis-stack:
    container_name: redis-stack
    image: redis/redis-stack:latest
    ports:
      - 6379:6379


  college-help-desk:
    image: ${DOCKER_USERNAME}/rag-service:latest
    container_name: rag-service
    ports:
      - "8080:8080"
    depends_on:
      ollama:
        condition: service_started
      elasticsearch:
        condition: service_started
    networks:
      - ollama-docker
    environment:
      - DOCKER_OLLAMA_HOST=${DOCKER_OLLAMA_HOST}
      - DOCKER_ELASTICSEARCH_HOST=${DOCKER_ELASTICSEARCH_HOST}


networks:
  ollama-docker:
    external: false