spring:
  application:
    name: college-help-desk\
  threads:
    virtual:
      enabled: true # For better scalability of one thread per request model
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4.1-mini
    retry:
      max-attempts: 10

  #    ollama:
#      base-url: http://localhost:11434
#      chat:
#        model: deepseek-r1:1.5b
#      embedding:
#        model: nomic-embed-text # dimension depends on model to model
  autoconfigure:
    exclude:
      - org.springframework.ai.vectorstore.elasticsearch.autoconfigure.ElasticsearchVectorStoreAutoConfiguration

elasticsearch:
  host: ${DOCKER_ELASTICSEARCH_HOST:localhost}
  port: 9200

embedding:
  dimensions: 768 # supported by nomic-embed-text, adjust if using a different model for VectorStore

# check ConversationMemoryService
conversation:
  memory:
    max-size: 10

# check QueryCacheService
vector-cache:
  similarity_threshold: 0.95 # check query similarity to query in vector cache

# check VectorSearchService
vector-database:
  top-k: 2
  similarity-threshold: 0.6 # check query similarity to content in vector database

redis:
  host: localhost
  port: 6379

chat-history:
  max-messages: 5




