spring:
  application:
    name: college-help-desk

  threads:
    virtual:
      enabled: true
# Note: if embedding model changes, need to reingest the old data as each embedding model will produce different vectors of their own
  ai:
    model:
      chat: google-genai
      embedding: none
    google:
      genai:
        api-key: ${GOOGLE_API_KEY}
        chat:
          options:
            model: gemini-3.1-flash-lite-preview

#    ollama:
#      base-url: http://localhost:11434
#      embedding:
#        options:
#          model: nomic-embed-text

    retry:
      max-attempts: 10

  autoconfigure:
    exclude:
      - org.springframework.ai.vectorstore.elasticsearch.autoconfigure.ElasticsearchVectorStoreAutoConfiguration

elasticsearch:
  host: ${DOCKER_ELASTICSEARCH_HOST:localhost}
  port: 9200

embedding:
  dimensions: 768

vector-cache:
  similarity_threshold: 0.95

vector-database:
  top-k: 2
  similarity-threshold: 0.6

redis:
  host: ${REDIS_HOST:localhost}
  port: 6379

chat-history:
  max-messages: 2